spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urp?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8888
