spring:
  profiles:
    active: dev #默认为开发环境
  thymeleaf:
    enabled: true
    suffix: .html
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8    #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8      #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
server:
  port: 8888
  error:
    path: /error

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.sercurity.entity
  mapper-locations: classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
